/* METADATA
{
    "name": "remote_kiyori",
    "display_name": {
        "zh": "远程 Kiyori",
        "en": "Remote Kiyori"
    },
    "description": {
        "zh": "通过局域网 HTTP API 调用另一台设备上的 Kiyori，用于跨设备协作。",
        "en": "Call another Kiyori device over the LAN HTTP API for cross-device collaboration."
    },
    "enabledByDefault": false,
    "category": "Network",
    "env": [
        {
            "name": "REMOTE_KIYORI_BASE_URL",
            "description": { "zh": "远程 Kiyori 地址，例如 http://192.168.1.23:8094", "en": "Remote Kiyori URL, for example http://192.168.1.23:8094" },
            "required": false
        },
        {
            "name": "REMOTE_KIYORI_TOKEN",
            "description": { "zh": "远程 Kiyori 的 Bearer Token", "en": "Bearer token of the remote Kiyori" },
            "required": false
        },
        {
            "name": "REMOTE_KIYORI_TIMEOUT_MS",
            "description": { "zh": "默认超时毫秒数，默认 60000", "en": "Default timeout in ms, default 60000" },
            "required": false
        }
    ],
    "tools": [
        {
            "name": "usage_advice",
            "description": {
                "zh": "远程 Kiyori 使用建议：\\n- 当另一台设备有本机没有的文件、应用或权限时，再使用 remote_kiyori_chat。\\n- 先用 remote_kiyori_configure 配置远程地址和 Token，再发起聊天。\\n- 优先把任务描述得具体一些，避免在两台设备之间反复追问。\\n- 这是对另一台 Kiyori 的远程委托，不要在未授权的情况下跨设备执行高风险操作。",
                "en": "Remote Kiyori advice:\\n- Use remote_kiyori_chat when another device has files, apps, or permissions this device lacks.\\n- Configure the remote URL and token with remote_kiyori_configure first.\\n- Make the delegated task specific to reduce back-and-forth across devices.\\n- This is a remote delegation to another Kiyori; avoid high-risk cross-device actions without explicit authorization."
            },
            "parameters": [],
            "advice": true
        },
        {
            "name": "remote_kiyori_configure",
            "description": {
                "zh": "配置并持久化远程 Kiyori 的 HTTP 连接参数，可选立即检测连接。",
                "en": "Configure and persist the remote Kiyori HTTP connection parameters, optionally testing the connection immediately."
            },
            "parameters": [
                {
                    "name": "base_url",
                    "description": { "zh": "远程 Kiyori Base URL，例如 http://192.168.1.23:8094", "en": "Remote Kiyori Base URL, for example http://192.168.1.23:8094" },
                    "type": "string",
                    "required": false
                },
                {
                    "name": "token",
                    "description": { "zh": "远程 Kiyori 的 Bearer Token", "en": "Bearer token of the remote Kiyori" },
                    "type": "string",
                    "required": false
                },
                {
                    "name": "timeout_ms",
                    "description": { "zh": "默认超时毫秒数（可选）", "en": "Default timeout in ms (optional)" },
                    "type": "number",
                    "required": false
                },
                {
                    "name": "test_connection",
                    "description": { "zh": "是否在保存后立即检测连接", "en": "Whether to test the connection right after saving" },
                    "type": "boolean",
                    "required": false
                }
            ]
        },
        {
            "name": "remote_kiyori_test_connection",
            "description": {
                "zh": "检测远程 Kiyori 的 HTTP 服务与 Bearer Token 是否可用。",
                "en": "Test whether the remote Kiyori HTTP service and Bearer token are available."
            },
            "parameters": [
                {
                    "name": "timeout_ms",
                    "description": { "zh": "本次检测超时毫秒数（可选）", "en": "Timeout for this test in ms (optional)" },
                    "type": "number",
                    "required": false
                }
            ]
        },
        {
            "name": "remote_kiyori_chat",
            "description": {
                "zh": "通过远程 Kiyori 的 /api/external-chat 接口同步发送一条聊天请求，并等待最终回复。",
                "en": "Send a synchronous chat request through the remote Kiyori /api/external-chat endpoint and wait for the final reply."
            },
            "parameters": [
                {
                    "name": "message",
                    "description": { "zh": "发送给远程 Kiyori 的消息内容", "en": "Message content sent to the remote Kiyori" },
                    "type": "string",
                    "required": true
                },
                {
                    "name": "request_id",
                    "description": { "zh": "请求 ID（可选，不传则由远程服务生成）", "en": "Request ID (optional; generated by the remote service when omitted)" },
                    "type": "string",
                    "required": false
                },
                {
                    "name": "group",
                    "description": { "zh": "与现有 Intent / HTTP 接口一致的 group 参数", "en": "The group parameter with the same semantics as the existing Intent / HTTP API" },
                    "type": "string",
                    "required": false
                },
                {
                    "name": "create_new_chat",
                    "description": { "zh": "是否先创建新对话", "en": "Whether to create a new chat first" },
                    "type": "boolean",
                    "required": false
                },
                {
                    "name": "chat_id",
                    "description": { "zh": "指定目标 chat_id（create_new_chat=false 时生效）", "en": "Target chat_id (used when create_new_chat=false)" },
                    "type": "string",
                    "required": false
                },
                {
                    "name": "create_if_none",
                    "description": { "zh": "没有可用会话时是否自动创建，默认 true", "en": "Whether to create a chat if none exists, default true" },
                    "type": "boolean",
                    "required": false
                },
                {
                    "name": "show_floating",
                    "description": { "zh": "是否让远程 Kiyori 显示悬浮聊天窗口", "en": "Whether the remote Kiyori should show the floating chat window" },
                    "type": "boolean",
                    "required": false
                },
                {
                    "name": "auto_exit_after_ms",
                    "description": { "zh": "远程悬浮窗自动退出毫秒数，可传 -1 关闭自动退出", "en": "Remote floating window auto-exit timeout in ms; use -1 to disable auto-exit" },
                    "type": "number",
                    "required": false
                },
                {
                    "name": "stop_after",
                    "description": { "zh": "请求结束后是否让远程聊天服务停止", "en": "Whether the remote chat service should stop after the request finishes" },
                    "type": "boolean",
                    "required": false
                },
                {
                    "name": "timeout_ms",
                    "description": { "zh": "本次请求超时毫秒数（可选）", "en": "Timeout for this request in ms (optional)" },
                    "type": "number",
                    "required": false
                }
            ]
        }
    ]
}
*/

type RemoteKiyoriConfigureParams = {
    base_url: string;
    token: string;
    timeout_ms?: number;
    test_connection?: boolean;
};

type RemoteKiyoriTestConnectionParams = {
    timeout_ms?: number;
};

type RemoteKiyoriChatParams = {
    message: string;
    request_id?: string;
    group?: string;
    create_new_chat?: boolean;
    chat_id?: string;
    create_if_none?: boolean;
    show_floating?: boolean;
    auto_exit_after_ms?: number;
    stop_after?: boolean;
    timeout_ms?: number;
};

type RemoteKiyoriConfig = {
    baseUrl: string;
    token: string;
    timeoutMs: number;
};

type RemoteKiyoriHttpResponse = {
    statusCode: number;
    content: string;
    url: string;
};

const remoteKiyoriTools = (function () {
    const PACKAGE_VERSION = "1.0.0";
    const DEFAULT_PORT = 8094;
    const DEFAULT_TIMEOUT_MS = 60000;

    const ENV_KEYS = {
        baseUrl: "REMOTE_KIYORI_BASE_URL",
        token: "REMOTE_KIYORI_TOKEN",
        timeoutMs: "REMOTE_KIYORI_TIMEOUT_MS"
    };

    function asText(value: unknown): string {
        if (value === undefined || value === null) return "";
        if (typeof value === "string") return value;
        throw new Error("Invalid text field in remote request or response");
    }

    function firstNonBlank(...values: Array<string | null | undefined>): string {
        for (let i = 0; i < values.length; i += 1) {
            const value = values[i];
            if (typeof value === "string" && value.trim()) {
                return value.trim();
            }
        }
        return "";
    }

    function readEnv(name: string): string {
        return (getEnv(name) ?? "").trim();
    }

    function ensureHttpScheme(raw: string): string {
        return raw.includes("://") ? raw : `http://${raw}`;
    }

    function normalizeBaseUrl(raw: string): string {
        const value = raw.trim().replace(/\/+$/g, "");
        if (!value) {
            throw new Error("Missing env: REMOTE_KIYORI_BASE_URL");
        }

        // 宿主 URI 解析器校验 authority；查询串或片段会吞掉随后追加的 API 路径。
        const URI = Java.type("java.net.URI");
        const uri = new URI(ensureHttpScheme(value));
        const scheme = uri.getScheme().toLowerCase();
        const host = uri.getHost();
        const declaredPort = uri.getPort();
        if ((scheme !== "http" && scheme !== "https") || !host ||
            uri.getRawUserInfo() !== null || uri.getRawQuery() !== null || uri.getRawFragment() !== null ||
            uri.getRawAuthority().endsWith(":") || declaredPort === 0 || declaredPort > 65535) {
            throw new Error("Invalid base_url: use an HTTP(S) host with an optional port/path, without credentials, query or fragment");
        }
        const port = declaredPort === -1 ? DEFAULT_PORT : declaredPort;
        const path = uri.getRawPath().replace(/\/+$/g, "");
        return `${scheme}://${host}:${port}${path}`;
    }

    function parseTimeout(value: number | undefined, defaultValue: number): number {
        if (value === undefined) {
            return defaultValue;
        }
        if (!Number.isSafeInteger(value) || value <= 0 || value > 2147483642000) {
            throw new Error("Invalid timeout_ms: expected positive integer");
        }
        return value;
    }

    function parseOptionalBoolean(value: boolean | undefined, fieldName: string): boolean | undefined {
        if (value === undefined) {
            return undefined;
        }
        if (typeof value !== "boolean") {
            throw new Error(`Invalid ${fieldName}: expected boolean`);
        }
        return value;
    }

    function coerceBoolean(value: unknown): boolean | undefined {
        return typeof value === "boolean" ? value : undefined;
    }

    function parseOptionalAutoExitMs(value: number | undefined): number | undefined {
        if (value === undefined) {
            return undefined;
        }
        if (!Number.isInteger(value) || value < -1) {
            throw new Error("Invalid auto_exit_after_ms: expected -1 or non-negative integer");
        }
        return value;
    }

    function toHttpTimeoutSeconds(timeoutMs: number): number {
        return Math.max(1, Math.ceil(timeoutMs / 1000));
    }

    function errorMessage(error: unknown): string {
        console.error("[remote_kiyori] Tool operation failed", error instanceof Error ? error.name : typeof error);
        if (typeof error === "string") return error;
        if (error !== null && typeof error === "object" && "message" in error && typeof error.message === "string") return error.message;
        return "Unknown remote tool error";
    }

    function parseJson(content: string): Record<string, unknown> {
        try {
            const parsed: unknown = JSON.parse(content);
            if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
                throw new Error("Expected a JSON object");
            }
            return parsed as Record<string, unknown>;
        } catch (error: unknown) {
            errorMessage(error);
            throw new Error("Remote response is not a valid JSON object");
        }
    }

    function toOptionalInt(value: unknown): number | undefined {
        if (value === undefined || value === null) {
            return undefined;
        }
        if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new Error("Invalid integer in remote response");
        return value;
    }

    async function writeEnvVar(key: string, value: string): Promise<void> {
        await Tools.SoftwareSettings.writeEnvironmentVariable(key, value);
    }

    function resolveConfig(overrides?: {
        baseUrl?: string;
        token?: string;
        timeoutMs?: number;
    }): RemoteKiyoriConfig {
        const baseUrlRaw = overrides?.baseUrl ?? readEnv(ENV_KEYS.baseUrl);
        const tokenRaw = overrides?.token ?? readEnv(ENV_KEYS.token);
        const timeoutRaw = readEnv(ENV_KEYS.timeoutMs);

        const baseUrl = normalizeBaseUrl(baseUrlRaw);
        const token = tokenRaw.trim();
        if (!token) {
            throw new Error("Missing env: REMOTE_KIYORI_TOKEN");
        }

        return {
            baseUrl,
            token,
            timeoutMs: parseTimeout(overrides?.timeoutMs !== undefined ? overrides.timeoutMs : (timeoutRaw ? Number(timeoutRaw) : undefined), DEFAULT_TIMEOUT_MS)
        };
    }

    async function httpRequest(
        config: RemoteKiyoriConfig,
        path: string,
        method: "GET" | "POST",
        body: Record<string, unknown> | null,
        timeoutMs: number
    ): Promise<RemoteKiyoriHttpResponse> {
        const timeoutSeconds = toHttpTimeoutSeconds(timeoutMs);
        const headers: Record<string, string> = {
            Accept: "application/json",
            Authorization: `Bearer ${config.token}`
        };
        if (body != null) {
            headers["Content-Type"] = "application/json; charset=utf-8";
        }

        const response = await Tools.Net.http({
            url: `${config.baseUrl}${path}`,
            method,
            headers,
            body: body || undefined,
            connect_timeout: Math.min(timeoutSeconds, 10),
            read_timeout: timeoutSeconds + 5,
            validateStatus: false
        });

        return {
            statusCode: response.statusCode,
            content: response.content,
            url: response.url
        };
    }

    async function performHealthCheck(config: RemoteKiyoriConfig, timeoutMs: number) {
        const response = await httpRequest(config, "/api/health", "GET", null, timeoutMs);
        const data = parseJson(response.content);
        const success = response.statusCode >= 200 && response.statusCode < 300 && data.status === "ok";
        if (success && (typeof data.version_name !== "string" || typeof data.port !== "number" ||
            typeof data.enabled !== "boolean" || typeof data.service_running !== "boolean")) {
            throw new Error("Remote health response is missing required fields");
        }

        return {
            success,
            packageVersion: PACKAGE_VERSION,
            remoteBaseUrl: config.baseUrl,
            status: asText(data.status),
            versionName: asText(data.version_name),
            port: toOptionalInt(data.port),
            enabled: coerceBoolean(data.enabled),
            serviceRunning: coerceBoolean(data.service_running),
            httpStatus: response.statusCode,
            error: success
                ? ""
                : firstNonBlank(asText(data.error), `HTTP ${response.statusCode}`)
        };
    }

    async function remote_kiyori_configure(params: RemoteKiyoriConfigureParams) {
        const persistedKeys: string[] = [];
        let configured = false;
        try {
            // 先校验完整输入，避免无效 token/超时把原先可用的配置写坏。
            if (typeof params.base_url !== "string" || typeof params.token !== "string") {
                throw new Error("base_url and token are required strings");
            }
            const config = resolveConfig({ baseUrl: params.base_url, token: params.token, timeoutMs: params.timeout_ms });
            const shouldTest = parseOptionalBoolean(params.test_connection, "test_connection") === true;
            await writeEnvVar(ENV_KEYS.baseUrl, config.baseUrl);
            persistedKeys.push(ENV_KEYS.baseUrl);
            await writeEnvVar(ENV_KEYS.token, config.token);
            persistedKeys.push(ENV_KEYS.token);

            if (params.timeout_ms !== undefined) {
                await writeEnvVar(ENV_KEYS.timeoutMs, String(config.timeoutMs));
                persistedKeys.push(ENV_KEYS.timeoutMs);
            }
            configured = true;

            const result: Record<string, unknown> = {
                success: true,
                configured: true,
                packageVersion: PACKAGE_VERSION,
                remoteBaseUrl: config.baseUrl,
                timeoutMs: config.timeoutMs,
                persistedKeys
            };

            if (shouldTest) {
                const health = await performHealthCheck(config, config.timeoutMs);
                result.success = health.success;
                result.health = health;
                if (!health.success) {
                    result.error = health.error;
                }
            }

            return result;
        } catch (error: unknown) {
            return {
                success: false,
                configured,
                persistedKeys,
                packageVersion: PACKAGE_VERSION,
                error: errorMessage(error)
            };
        }
    }

    async function remote_kiyori_test_connection(params: RemoteKiyoriTestConnectionParams = {}) {
        try {
            const config = resolveConfig();
            const timeoutMs = parseTimeout(params.timeout_ms, config.timeoutMs);
            return await performHealthCheck(config, timeoutMs);
        } catch (error: unknown) {
            return {
                success: false,
                packageVersion: PACKAGE_VERSION,
                error: errorMessage(error)
            };
        }
    }

    function buildChatBody(params: RemoteKiyoriChatParams): Record<string, unknown> {
        const message = asText(params.message).trim();
        if (!message) throw new Error("Missing required parameter: message");
        const body: Record<string, unknown> = {
            message,
            response_mode: "sync"
        };

        const requestId = asText(params.request_id).trim();
        if (requestId) {
            body.request_id = requestId;
        }

        const group = asText(params.group).trim();
        if (group) {
            body.group = group;
        }

        const createNewChat = parseOptionalBoolean(params.create_new_chat, "create_new_chat");
        if (createNewChat !== undefined) {
            body.create_new_chat = createNewChat;
        }

        const chatId = asText(params.chat_id).trim();
        if (chatId) {
            body.chat_id = chatId;
        }

        const createIfNone = parseOptionalBoolean(params.create_if_none, "create_if_none");
        if (createIfNone !== undefined) {
            body.create_if_none = createIfNone;
        }

        const showFloating = parseOptionalBoolean(params.show_floating, "show_floating");
        if (showFloating !== undefined) {
            body.show_floating = showFloating;
        }

        const autoExitAfterMs = parseOptionalAutoExitMs(params.auto_exit_after_ms);
        if (autoExitAfterMs !== undefined) {
            body.auto_exit_after_ms = autoExitAfterMs;
        }

        const stopAfter = parseOptionalBoolean(params.stop_after, "stop_after");
        if (stopAfter !== undefined) {
            body.stop_after = stopAfter;
        }

        return body;
    }

    async function remote_kiyori_chat(params: RemoteKiyoriChatParams) {
        let config: RemoteKiyoriConfig | null = null;
        let requestBody: Record<string, unknown> | null = null;
        try {
            config = resolveConfig();
            const timeoutMs = parseTimeout(params.timeout_ms, config.timeoutMs);
            requestBody = buildChatBody(params);
            // 远端执行期限必须随请求发送，不能只让本地 HTTP 等待结束。
            requestBody.timeout_ms = timeoutMs;

            const response = await httpRequest(
                config,
                "/api/external-chat",
                "POST",
                requestBody,
                timeoutMs
            );
            const data = parseJson(response.content);
            if (typeof data.success !== "boolean") throw new Error("Remote chat response is missing success");
            const success = response.statusCode >= 200 && response.statusCode < 300 && data.success;

            return {
                success,
                packageVersion: PACKAGE_VERSION,
                remoteBaseUrl: config.baseUrl,
                requestId: firstNonBlank(asText(data.request_id), asText(requestBody.request_id)),
                chatId: asText(data.chat_id).trim(),
                aiResponse: asText(data.ai_response),
                httpStatus: response.statusCode,
                error: success ? "" : firstNonBlank(asText(data.error), `HTTP ${response.statusCode}`)
            };
        } catch (error: unknown) {
            return {
                success: false,
                packageVersion: PACKAGE_VERSION,
                remoteBaseUrl: config ? config.baseUrl : "",
                requestId: requestBody ? asText(requestBody.request_id).trim() : "",
                error: errorMessage(error)
            };
        }
    }

    return {
        remote_kiyori_configure,
        remote_kiyori_test_connection,
        remote_kiyori_chat
    };
})();

exports.remote_kiyori_configure = remoteKiyoriTools.remote_kiyori_configure;
exports.remote_kiyori_test_connection = remoteKiyoriTools.remote_kiyori_test_connection;
exports.remote_kiyori_chat = remoteKiyoriTools.remote_kiyori_chat;
