/* METADATA
{
  "name": "bilibili",
  "display_name": {
    "zh": "哔哩哔哩",
    "en": "Bilibili"
  },
  "description": {
    "zh": "检索哔哩哔哩视频、字幕、弹幕、评论和账号只读数据，并按用户要求导出媒体与分析产物。",
    "en": "Read-only Bilibili video, subtitle, danmaku, comment, and account research with user-requested media and analysis exports."
  },
  "enabledByDefault": false,
  "category": "Media",
  "tools": [
    {"name":"bilibili_doctor","description":{"zh":"检查 Bilibili 登录状态和宿主媒体能力。","en":"Check Bilibili login state and host media capabilities."},"parameters":[]},
    {"name":"bilibili_resolve","description":{"zh":"解析 Bilibili 视频、番剧或短链接目标。","en":"Resolve a Bilibili video, season, episode, or short URL target."},"parameters":[{"name":"target","description":{"zh":"Bilibili URL、BV/av、EP、SS 或 MD 标识。","en":"Bilibili URL or BV/av, EP, SS, or MD identifier."},"type":"string","required":true},{"name":"part","description":{"zh":"可选分P编号。","en":"Optional page number."},"type":"number","required":false}]},
    {"name":"bilibili_search","description":{"zh":"搜索 Bilibili 视频。","en":"Search Bilibili videos."},"parameters":[{"name":"keyword","description":{"zh":"搜索关键词。","en":"Search keyword."},"type":"string","required":true},{"name":"page","description":{"zh":"页码。","en":"Page number."},"type":"number","required":false},{"name":"pages","description":{"zh":"页数。","en":"Number of pages."},"type":"number","required":false},{"name":"limit","description":{"zh":"结果上限。","en":"Result limit."},"type":"number","required":false},{"name":"order","type":"string","required":false,"description":{"zh":"搜索排序 totalrank/click/pubdate/dm/stow。","en":"order"}},{"name":"duration","type":"number","required":false,"description":{"zh":"搜索时长分组，0至4。","en":"duration"}}]},
    {"name":"bilibili_info","description":{"zh":"获取视频信息。","en":"Get video information."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","description":{"zh":"可选分P编号。","en":"Optional page number."},"type":"number","required":false}]},
    {"name":"bilibili_season","description":{"zh":"获取番剧或影视季信息。","en":"Get season information."},"parameters":[{"name":"target","description":{"zh":"EP、SS 或 MD 目标。","en":"EP, SS, or MD target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}}]},
    {"name":"bilibili_subtitles","description":{"zh":"获取并导出字幕。","en":"Fetch and export subtitles."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"language","type":"string","required":false,"description":{"zh":"字幕语言代码。","en":"language"}},{"name":"all_languages","type":"boolean","required":false,"description":{"zh":"导出所有字幕语言。","en":"all_languages"}},{"name":"format","type":"string","required":false,"description":{"zh":"导出格式；字幕 json/srt/vtt/txt/ass/all，弹幕 xml/json/txt/ass/all。","en":"format"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}},{"name":"inline_limit","type":"number","required":false,"description":{"zh":"内联字幕条数，0至200，默认0。","en":"inline_limit"}}]},
    {"name":"bilibili_danmaku","description":{"zh":"获取并导出当前弹幕。","en":"Fetch and export current danmaku."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"format","type":"string","required":false,"description":{"zh":"导出格式；字幕 json/srt/vtt/txt/ass/all，弹幕 xml/json/txt/ass/all。","en":"format"}},{"name":"limit","type":"number","required":false,"description":{"zh":"返回条数上限，按工具限制校验。","en":"limit"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}},{"name":"inline","type":"boolean","required":false,"description":{"zh":"是否内联返回弹幕。","en":"inline"}},{"name":"width","type":"number","required":false,"description":{"zh":"输出图像宽度。","en":"width"}},{"name":"height","type":"number","required":false,"description":{"zh":"弹幕画布高度。","en":"height"}},{"name":"source","type":"string","required":false,"description":{"zh":"当前弹幕来源：segments（默认，最多50段）或xml；两种来源分别执行，不自动切换。","en":"segments (default, at most 50 segments) or xml; no automatic source switching."}}]},
    {"name":"bilibili_comments","description":{"zh":"获取并导出评论。","en":"Fetch and export comments."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"sort","type":"string","required":false,"description":{"zh":"评论排序 hot/time。","en":"sort"}},{"name":"pages","type":"number","required":false,"description":{"zh":"请求页数，按工具限制校验。","en":"pages"}},{"name":"limit","type":"number","required":false,"description":{"zh":"返回条数上限，按工具限制校验。","en":"limit"}},{"name":"include_replies","type":"boolean","required":false,"description":{"zh":"是否保留回复。","en":"include_replies"}},{"name":"reply_pages","type":"number","required":false,"description":{"zh":"每根评论额外回复页数，0至2。","en":"reply_pages"}},{"name":"reply_limit","type":"number","required":false,"description":{"zh":"回复条数上限，0至100。","en":"reply_limit"}},{"name":"output","type":"boolean","required":false,"description":{"zh":"是否写入文件，默认false。","en":"output"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]},
    {"name":"bilibili_user","description":{"zh":"获取用户公开信息。","en":"Get public user information."},"parameters":[{"name":"user","description":{"zh":"用户 UID 或空间 URL。","en":"User UID or space URL."},"type":"string","required":true},{"name":"full","type":"boolean","required":false,"description":{"zh":"额外请求WBI空间资料并返回profile；字段由平台公开范围决定，不保证注册时间等字段。","en":"Request the WBI space profile and return it as profile; only fields exposed by the platform are available."}}]},
    {"name":"bilibili_account","description":{"zh":"获取当前账号的只读列表。","en":"Read current-account lists."},"parameters":[{"name":"kind","description":{"zh":"history、watch_later、favorites、favorite_items、liked、coins、followed_bangumi、followed_cinema、submissions；全部只读。","en":"List type."},"type":"string","required":true},{"name":"mid","type":"number","required":false,"description":{"zh":"目标用户UID；未提供时使用当前账号。","en":"mid"}},{"name":"folder_id","type":"number","required":false,"description":{"zh":"收藏夹ID；favorite_items必填。","en":"folder_id"}},{"name":"page","type":"number","required":false,"description":{"zh":"起始页码，从1开始。","en":"page"}},{"name":"pages","type":"number","required":false,"description":{"zh":"请求页数，按工具限制校验。","en":"pages"}},{"name":"page_size","type":"number","required":false,"description":{"zh":"每页条数。","en":"page_size"}},{"name":"limit","type":"number","required":false,"description":{"zh":"返回条数上限，按工具限制校验。","en":"limit"}},{"name":"keyword","type":"string","required":false,"description":{"zh":"检索关键词。","en":"keyword"}},{"name":"history_type","type":"string","required":false,"description":{"zh":"历史记录类型 all、archive、pgc、live 或 article。","en":"history_type"}},{"name":"output","type":"boolean","required":false,"description":{"zh":"是否写入文件，默认false。","en":"output"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]},
    {"name":"bilibili_interactive","description":{"zh":"导出互动视频图。","en":"Export an interactive-video graph."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"start_edge","type":"number","required":false,"description":{"zh":"互动图起始节点，默认0。","en":"start_edge"}},{"name":"max_nodes","type":"number","required":false,"description":{"zh":"互动节点上限，1至100。","en":"max_nodes"}},{"name":"output","type":"boolean","required":false,"description":{"zh":"是否写入文件，默认false。","en":"output"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]},
    {"name":"bilibili_summary","description":{"zh":"请求站内 AI 摘要。","en":"Request the site AI summary."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"include_transcript","type":"boolean","required":false,"description":{"zh":"是否附带站内返回的摘要文本内容。","en":"include_transcript"}},{"name":"output","type":"boolean","required":false,"description":{"zh":"是否写入文件，默认false。","en":"output"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]},
    {"name":"bilibili_formats","description":{"zh":"列出可用媒体格式。","en":"List available media formats."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"quality","type":"string","required":false,"description":{"zh":"best、360p、480p、720p、720p60、1080p、1080p+、1080p60、4k、hdr、dolby、8k。","en":"quality"}}]},
    {"name":"bilibili_download","description":{"zh":"下载并处理媒体，使用 Kiyori 内置 FFmpeg。","en":"Download and process media using Kiyori built-in FFmpeg."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"quality","type":"string","required":false,"description":{"zh":"best、360p、480p、720p、720p60、1080p、1080p+、1080p60、4k、hdr、dolby、8k。","en":"quality"}},{"name":"video_codec","type":"string","required":false,"description":{"zh":"视频编码 avc、hevc 或 av1；不传时使用该清晰度的首个可用编码。","en":"video_codec"}},{"name":"container","type":"string","required":false,"description":{"zh":"视频封装 mp4/mkv。","en":"container"}},{"name":"audio_only","type":"boolean","required":false,"description":{"zh":"仅下载音频。","en":"audio_only"}},{"name":"audio_format","type":"string","required":false,"description":{"zh":"音频格式 m4a/mp3/flac/wav/opus。","en":"audio_format"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}},{"name":"clip_start","type":"number","required":false,"description":{"zh":"剪辑开始秒数，与clip_end一起提供。","en":"clip_start"}},{"name":"clip_end","type":"number","required":false,"description":{"zh":"剪辑结束秒数，必须大于clip_start。","en":"clip_end"}}]},
    {"name":"bilibili_frames","description":{"zh":"从本地媒体提取关键帧。","en":"Extract keyframes from local media."},"parameters":[{"name":"input_path","description":{"zh":"媒体路径。","en":"Media path."},"type":"string","required":true},{"name":"output_directory","type":"string","required":false,"description":{"zh":"抽帧输出目录，Android绝对路径。","en":"output_directory"}},{"name":"count","type":"number","required":false,"description":{"zh":"抽帧数量，1至30，默认8。","en":"count"}},{"name":"width","type":"number","required":false,"description":{"zh":"输出图像宽度。","en":"width"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]},
    {"name":"bilibili_capture","description":{"zh":"一次性抓取视频信息及所选附加产物。","en":"Capture video information and selected artifacts in one run."},"parameters":[{"name":"target","description":{"zh":"目标。","en":"Target."},"type":"string","required":true},{"name":"part","type":"number","required":false,"description":{"zh":"分P编号，从1开始。","en":"part"}},{"name":"subtitles","type":"boolean","required":false,"description":{"zh":"是否抓取字幕，默认true。","en":"subtitles"}},{"name":"subtitle_format","type":"string","required":false,"description":{"zh":"字幕导出格式，默认all。","en":"subtitle_format"}},{"name":"danmaku","type":"boolean","required":false,"description":{"zh":"是否抓取弹幕，默认true。","en":"danmaku"}},{"name":"danmaku_format","type":"string","required":false,"description":{"zh":"弹幕导出格式，默认all。","en":"danmaku_format"}},{"name":"danmaku_limit","type":"number","required":false,"description":{"zh":"弹幕条数上限，默认1000。","en":"danmaku_limit"}},{"name":"comments","type":"boolean","required":false,"description":{"zh":"是否抓取评论，默认true。","en":"comments"}},{"name":"comment_limit","type":"number","required":false,"description":{"zh":"评论条数上限，默认20。","en":"comment_limit"}},{"name":"summary","type":"boolean","required":false,"description":{"zh":"是否抓取站内AI摘要，默认true。","en":"summary"}},{"name":"media","type":"boolean","required":false,"description":{"zh":"是否下载媒体，默认false。","en":"media"}},{"name":"quality","type":"string","required":false,"description":{"zh":"best、360p、480p、720p、720p60、1080p、1080p+、1080p60、4k、hdr、dolby、8k。","en":"quality"}},{"name":"video_codec","type":"string","required":false,"description":{"zh":"视频编码 avc、hevc 或 av1；不传时使用该清晰度的首个可用编码。","en":"video_codec"}},{"name":"container","type":"string","required":false,"description":{"zh":"视频封装 mp4/mkv。","en":"container"}},{"name":"frames","type":"boolean","required":false,"description":{"zh":"是否抽帧，需同时启用media。","en":"frames"}},{"name":"frame_count","type":"number","required":false,"description":{"zh":"抽帧数量，默认8。","en":"frame_count"}},{"name":"output_root","type":"string","required":false,"description":{"zh":"Android绝对输出根目录，默认 /sdcard/Download/Kiyori/Bilibili。","en":"output_root"}},{"name":"overwrite","type":"boolean","required":false,"description":{"zh":"是否覆盖已有产物，默认false。","en":"overwrite"}}]}
  ]
}
*/

import {
  account,
  capture,
  comments,
  danmaku,
  doctor,
  download,
  formats,
  frames,
  info,
  interactive,
  resolve,
  search,
  season,
  subtitles,
  summary,
  user
} from "../lib/operations";

import { toolOperation } from "../lib/errors";

export const bilibili_account = toolOperation(account);
export const bilibili_capture = toolOperation(capture);
export const bilibili_comments = toolOperation(comments);
export const bilibili_danmaku = toolOperation(danmaku);
export const bilibili_doctor = toolOperation(doctor);
export const bilibili_download = toolOperation(download);
export const bilibili_formats = toolOperation(formats);
export const bilibili_frames = toolOperation(frames);
export const bilibili_info = toolOperation(info);
export const bilibili_interactive = toolOperation(interactive);
export const bilibili_resolve = toolOperation(resolve);
export const bilibili_search = toolOperation(search);
export const bilibili_season = toolOperation(season);
export const bilibili_subtitles = toolOperation(subtitles);
export const bilibili_summary = toolOperation(summary);
export const bilibili_user = toolOperation(user);
